### ISSUE TITLE
Comentarios avance1

### ISSUE THREAD

**Issue by AliciaMstt** [bbeennjjaammiinn/proyecto_final_Bennjamin_Corona_Comunidad#2]
OK

Cuida tu formato md, dejaste todo en negritas

**Comment by bbeennjjaammiinn** [comment]
saludos! ya lo cambie

**Comment by AzaleaGuerra** [comment]
¿De qué especie son los datos? ¿Es resecuenciación de genomas completos?

**Comment by bbeennjjaammiinn** [comment]
son especies del genero Vibrio, es secuenciación de genomas completos

**Comment by AzaleaGuerra** [comment]
Ok. Ya puedes cerrar el issue.
